=== Alex72005/Lenguajes2024_Alejandro_Santos/segundo_trimestre/tema10/ejerciciosXML/ej3/ej3.dtd
<!ELEMENT menu (item+)>
<!ELEMENT item (nombre,descripcion,precio,categoria)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT categoria (#PCDATA)>

=== Alex72005/Lenguajes2024_Alejandro_Santos/segundo_trimestre/tema10/ejerciciosXML/ej3/ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE menu SYSTEM "ej3.dtd"> -->
<!-- Hecho por Alejandro Santos-->
<?xml-model href="ej3.xsd"?>
<menu>
    <item>
        <nombre>Ensalada César</nombre>
        <descripcion>Lechuga, pollo, crutones, queso parmesano y aderezo César</descripcion>
        <precio moneda="EUR">8.50</precio>
        <categoria>Entrante</categoria>
    </item>
    <item>
        <nombre>Paella Valenciana</nombre>
        <descripcion>Arroz con mariscos, pollo, conejo y verduras</descripcion>
        <precio moneda="EUR">15.00</precio>
        <categoria>Plato principal</categoria>
    </item>
    <item>
        <nombre>Tiramisú</nombre>
        <descripcion>Postre italiano con capas de bizcocho y crema de mascarpone</descripcion>
        <precio moneda="EUR">5.50</precio>
        <categoria>Postre</categoria>
    </item>
</menu>
