=== Alex72005/Lenguajes2024_Alejandro_Santos/segundo_trimestre/tema10/ejerciciosXML/ej2/ej2.dtd
<!-- Hecho por Alejandro Santos-->
<!ELEMENT agenda (contacto+)>
<!ELEMENT contacto (nombre,telefono,email,direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (movil|fijo) #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT direccion (calle,ciudad,codigo_postal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>

=== Alex72005/Lenguajes2024_Alejandro_Santos/segundo_trimestre/tema10/ejerciciosXML/ej2/ej2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE agenda SYSTEM "ej2.dtd"> -->
<?xml-model href="ej2.xsd"?>
<agenda>
    <contacto>
        <nombre>Juan Pérez</nombre>
        <telefono tipo="movil">+34 600 123 456</telefono>
        <email>juan.perez@example.com</email>
        <direccion>
            <calle>Calle Mayor 10</calle>
            <ciudad>Madrid</ciudad>
            <codigo_postal>28013</codigo_postal>
        </direccion>
    </contacto>
    <contacto>
        <nombre>María López</nombre>
        <telefono tipo="fijo">+34 915 678 901</telefono>
        <email>maria.lopez@example.com</email>
        <direccion>
            <calle>Gran Vía 22</calle>
            <ciudad>Barcelona</ciudad>
            <codigo_postal>08010</codigo_postal>
        </direccion>
    </contacto>
</agenda>
