=== Alex72005/Lenguajes2024_Alejandro_Santos/segundo_trimestre/tema10/ejerciciosXML/ej4/ej4.dtd
<!ELEMENT dni (numero,letra,nombre,apellidos,fecha_nacimiento,nacionalidad,direccion,sexo,fecha_emision,fecha_caducidad)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT letra (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT direccion (calle,ciudad,codigo_postal,provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT fecha_emision (#PCDATA)>
<!ELEMENT fecha_caducidad (#PCDATA)>

=== Alex72005/Lenguajes2024_Alejandro_Santos/segundo_trimestre/tema10/ejerciciosXML/ej4/ej4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE dni SYSTEM "ej4.dtd"> -->
<!-- Hecho por Alejandro Santos-->
<?xml-model href="ej4.xsd"?>
<dni>
    <numero>1234678</numero>
    <letra>Z</letra>
    <nombre>Juan</nombre>
    <apellidos>Pérez García</apellidos>
    <fecha_nacimiento>1990-05-15</fecha_nacimiento>
    <nacionalidad>Española</nacionalidad>
    <direccion>
        <calle>Calle Mayor 10</calle>
        <ciudad>Madrid</ciudad>
        <codigo_postal>28013</codigo_postal>
        <provincia>Madrid</provincia>
    </direccion>
    <sexo>Hombre</sexo>
    <fecha_emision>2020-01-01</fecha_emision>
    <fecha_caducidad>2030-01-01</fecha_caducidad>
</dni>
