=== Alex72005/Lenguajes2024_Alejandro_Santos/segundo_trimestre/tema10/ejerciciosXML/ej7/ej7.dtd
<!ELEMENT configuracion (informacion,base_datos,usuario,parametros)>
<!ELEMENT informacion (nombre,version,autor)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT base_datos (host,puerto,usuario,contrase침a,nombre_bd)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT puerto (#PCDATA)>
<!ELEMENT usuario (#PCDATA|tema|idioma|preferencias)*>
<!ELEMENT contrase침a (#PCDATA)>
<!ELEMENT nombre_bd (#PCDATA)>
<!ELEMENT tema (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT preferencias (notificaciones,modo_autom치tico)>
<!ELEMENT notificaciones (#PCDATA)>
<!ELEMENT modo_autom치tico (#PCDATA)>
<!ELEMENT parametros (maximo_intentos,modo_debug,registro)>
<!ELEMENT maximo_intentos (#PCDATA)>
<!ELEMENT modo_debug (#PCDATA)>
<!ELEMENT registro (#PCDATA)>

=== Alex72005/Lenguajes2024_Alejandro_Santos/segundo_trimestre/tema10/ejerciciosXML/ej7/ej7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Hecho por Alejandro Santos-->
<!--<!DOCTYPE configuracion SYSTEM "ej7.dtd"> -->
<?xml-model href="ej7.xsd"?>
<configuracion>
    <informacion>
        <nombre>MiAplicacion</nombre>
        <version>1.0.0</version>
        <autor>Juan Pérez</autor>
    </informacion>
    
    <base_datos>
        <host>localhost</host>
        <puerto>3306</puerto>
        <usuario>admin</usuario>
        <contraseña>password123</contraseña>
        <nombre_bd>mi_base_de_datos</nombre_bd>
    </base_datos>
    
    <usuario>
        <tema>oscuro</tema>
        <idioma>es</idioma>
        <preferencias>
            <notificaciones>activadas</notificaciones>
            <modo_automático>desactivado</modo_automático>
        </preferencias>
    </usuario>
    
    <parametros>
        <maximo_intentos>5</maximo_intentos>
        <modo_debug>desactivado</modo_debug>
        <registro>log.txt</registro>
    </parametros>
</configuracion>
